// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6H7bjsnaa2-YcryHyT7BADlrXI7EvPXo',
    appId: '1:339680593433:web:f1c305c2ca678c4235cc88',
    messagingSenderId: '339680593433',
    projectId: 'vendingapp-8a1ff',
    authDomain: 'vendingapp-8a1ff.firebaseapp.com',
    storageBucket: 'vendingapp-8a1ff.appspot.com',
    measurementId: 'G-T3GSBPNNSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzFlAW-BBltT0MuIYio5LLhsbcDZ5o-5M',
    appId: '1:339680593433:android:704b07404b0e7a9c35cc88',
    messagingSenderId: '339680593433',
    projectId: 'vendingapp-8a1ff',
    storageBucket: 'vendingapp-8a1ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOGxOn1pT_ZAo34D_PgGW1zhrtgmpyfxE',
    appId: '1:339680593433:ios:e63a2a9f8e1c8c3e35cc88',
    messagingSenderId: '339680593433',
    projectId: 'vendingapp-8a1ff',
    storageBucket: 'vendingapp-8a1ff.appspot.com',
    iosBundleId: 'com.example.vendingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOGxOn1pT_ZAo34D_PgGW1zhrtgmpyfxE',
    appId: '1:339680593433:ios:e08f8bde825ac28f35cc88',
    messagingSenderId: '339680593433',
    projectId: 'vendingapp-8a1ff',
    storageBucket: 'vendingapp-8a1ff.appspot.com',
    iosBundleId: 'com.example.vendingApp.RunnerTests',
  );
}
